[package]
name = "mips_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
colorful = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
mips_vm = { path = "../vm" }
